#!/usr/bin/with-contenv bash

### Set Debug Mode

DEBUG_MODE=${DEBUG_MODE:-"FALSE"}

if [[ "$DEBUG_MODE" = "TRUE" ]] && [[ "$DEBUG_MODE" = "true" ]]; then
	set -x
	DEBUG_ARG="--debug" 
fi

### Setup Persistent Storage
if [ ! -d /data ]; then
	mkdir -p /data
fi

    chown -R clamav:clamav /data

### Setup Cron
echo '* 1 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt
echo '* 5 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt
echo '* 9 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt
echo '* 13 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt
echo '* 17 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt
echo '* 21 * * * freshclam --user=clamav --verbose --log=/var/log/clamav/freshclam.log $DEBUG_ARG >/dev/null 2>&1' >>/assets/cron/crontab.txt

### Setup Logs
mkdir -p /var/log/clamav
chown -R clamav:clamav /var/log/clamav

### Check for Definitions
if [ ! -f /data/main.cvd  ]; then
        echo '** [clamav] No Definitions Found, Downloading..'
	freshclam --user=clamav --verbose --show-progress --log=/var/log/clamav/freshclam.log $DEBUG_ARG
fi


mkdir -p /tmp/state
touch /tmp/state/10-clamd-init
