#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service both 10-clamd
PROCESS_NAME="freshclam"

check_container_initialized

date >/dev/null

if [ "$1" != "NOW" ]; then
    sleep 10
    liftoff
elif [ "$1" = "NOW" ]; then
    DEFINITIONS_UPDATE_BEGIN=+0
    MANUAL=TRUE
fi

### Container Startup
print_notice "Definitions Updating Routines Initialized on $(date)"

### Wait for Next time to start backup
  current_time=$(date +"%s")
  today=$(date +"%Y%m%d")

  if [[ $DEFINITIONS_UPDATE_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
  else
        target_time=$(date --date="${today}${DEFINITIONS_UPDATE_BEGIN}" +"%s")
    if [[ "$target_time" < "$current_time" ]]; then
        target_time=$(($target_time + 24*60*60))
    fi
  waittime=$(($target_time - $current_time))
  fi

  sleep $waittime

  while true; do
    print_info "Downloading Latest Definitions"
  	silent exec freshclam -F --config-file="${CONFIG_LOCATION}""${FRESHCLAM_CONFIG_FILE}" --daemon-notify "${CONFIG_LOCATION}""${CLAMD_CONFIG_FILE}" "${log_verbose}" "${freshclam_log}" "${debug_arg}"
### Go back to Sleep until next definitions update time
   if [ "$MANUAL" = "TRUE" ]; then
        exit 0;
   else
   	    print_debug "Sleeping for $DEFINITIONS_UPDATE_FREQUENCY minutes"
        sleep $(($DEFINITIONS_UPDATE_FREQUENCY*60))
   fi
done
