#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="clamav"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting ClamAV"
clamd --config-file ${CONFIG_LOCATION}${CLAMD_CONFIG_FILE} ${debug_arg}
