#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="clamav"

check_container_initialized
check_service_initialized init
liftoff

### Set Debug Mode
if [ "$DEBUG_MODE"="TRUE" ] || [ "$DEBUG_MODE"="true" ]; then
	DEBUG_MODE="--debug" 
fi

liftoff

print_info "Starting ClamAV"
exec s6-setuidgid clamav clamd $DEBUG_MODE
